name: Amazon Watcher

on:
  schedule:
    - cron:  '*/1 * * * *'
  workflow_dispatch:

jobs:
  watch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install browser runtime & place Chromedriver
        run: |
          sudo apt-get update
          # Install Chromium (headless-capable)
          sudo apt-get install -y chromium-browser

          # Copy your bundled Chromedriver into PATH
          sudo mv bin/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

          # Sanity-check
          which chromedriver
          which chromium-browser

      - name: Install Python deps
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run Amazon Watcher
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          CHECK_INTERVAL: 10
          LOG: true
          CHROMEDRIVER_PATH: /usr/local/bin/chromedriver
          # Point Selenium to use the system Chromium binary
          BROWSER_BINARY: /usr/bin/chromium-browser
        run: python main.py
