name: Amazon Watcher

on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  watch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Chrome for Testing & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq unzip

          # 1) Fetch latest stable version number
          LATEST=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json \
            | jq -r '.channels.Stable.version')

          echo "Using Chrome for Testing version: $LATEST"

          # 2) Download & unzip Chrome for Testing
          wget -q -O chrome-linux64.zip \
            "https://storage.googleapis.com/chrome-for-testing-public/${LATEST}/linux64/chrome-linux64.zip"
          unzip -q chrome-linux64.zip -d chrome-bin

          # 3) Download & unzip matching Chromedriver
          wget -q -O chromedriver-linux64.zip \
            "https://storage.googleapis.com/chrome-for-testing-public/${LATEST}/linux64/chromedriver-linux64.zip"
          unzip -q chromedriver-linux64.zip

          # 4) Move binaries into PATH
          sudo mv chrome-bin/chrome-linux64/* /usr/local/bin/
          sudo mv chromedriver /usr/local/bin/chromedriver

          sudo chmod +x /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/google-chrome-stable || true

          # Verify
          which chromedriver
          which google-chrome

      - name: Install Python deps
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run Amazon Watcher
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          CHECK_INTERVAL: 10
          LOG: true
          CHROMEDRIVER_PATH: /usr/local/bin/chromedriver
        run: python main.py
